# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7d9c68563464ee088945cc83400e08bcb32673a0d3557188fca1672d72b780613855ac5968fa5268ab0caaf168a11a2acced38c989b9d9fac66a7c1d2bf00926

test:
  secret_key_base: 2253db7e6a48834769a18ca8910f6c4973de1ac5e8f8a00263929b1d1d07b6cddd1c9ceab77dfc856b730bd8c018c6bb8013a2374202289e8fb96affee074fb3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
